import { DaemonClient } from "@bremio/daemon-client";
import { c } from "./ui";

const USAGE = `
Usage: bremio run-info <runId> <command>

Commands:
  context       List blackboard (context) entries for the run
  artifacts     List artifacts generated by the run
`;

export async function runInfoCommandFromCli(positionals: string[], repoPath: string): Promise<number> {
  const runId = positionals[1];
  const subcommand = positionals[2];

  if (!runId || !subcommand) {
    console.log(USAGE);
    return 2;
  }

  const client = new DaemonClient(Number(process.env.BREMIO_DAEMON_PORT) || 9229);

  try {
    if (subcommand === "context") {
      const { entries } = await client.getBlackboardEntries(runId);
      if (entries.length === 0) {
        console.log("No context (blackboard) entries found.");
        return 0;
      }
      for (const entry of entries) {
        console.log(c.cyan(`[${entry.kind}]`) + ` ${entry.id}`);
        console.log(`  Author:   ${entry.author}`);
        console.log(`  Created:  ${new Date(entry.createdAt).toLocaleString()}`);
        console.log(`\n  ${entry.content}\n`);
      }
      return 0;
    }

    if (subcommand === "artifacts") {
      const { artifacts } = await client.runDetail(runId, repoPath);
      if (!artifacts || artifacts.length === 0) {
        console.log("No artifacts found for this run.");
        return 0;
      }
      for (const artifact of artifacts) {
        console.log(c.cyan(`[${artifact.kind}]`) + ` ${artifact.path}`);
        if (artifact.taskId) {
          console.log(`  Source Task: ${artifact.taskId}`);
        }
        console.log(`  Created:     ${new Date(artifact.createdAt).toLocaleString()}`);
        console.log("");
      }
      return 0;
    }

    console.log(`Unknown run-info command: ${subcommand}`);
    console.log(USAGE);
    return 2;
  } catch (error: any) {
    console.error(c.red("Error querying run info:"), error.message);
    return 1;
  }
}
